name: Run Payment
on:
  workflow_dispatch:
    inputs:
      snap_token:
        description: 'Midtrans Snap Token'
        required: false
        type: string

jobs:
  run-payment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Payment Script
        env:
          SNAP_TOKEN: ${{ inputs.snap_token }}
        run: |
          python run.py
